language: php
sudo: false

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    include:
        - php: 7.4
        - php: 8.0
    fast_finish: true

before_install:
    - composer self-update

install:
    - composer install --no-progress --optimize-autoloader --ignore-platform-req=php

script:
    - ./vendor/bin/phpcs
    - php ./src/benchmark.php

after_success:
    - bash <(curl -s https://codecov.io/bash) -f coverage.xml
