name: BenchMark
on: [push, pull_request]

jobs:
  benchmark:
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4', '8.0']
        composer-flags: ["--ignore-platform-req=php"]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: bcmath, mbstring, intl, sodium, json, opcache, apcu
          coverage: none
          tools: composer:v2, cs2pr
          ini-values: memory_limit=-1

      - name: Install dependencies
        run: composer update --no-progress --optimize-autoloader ${{ matrix.composer-flags }}

      - name: Check Coding Standard
        run: vendor/bin/phpcs

      - name: Run BenchMark Assessment
        run: vendor/bin/phpbench run --report default --revs 100 --iterations 5
